#!/usr/bin/env sh


DOTFILES_LOCAL="${DOTFILES_LOCAL:-$HOME/.dotfiles_local}"; export DOTFILES_LOCAL;

# Updates the `dotfiles_local` repo and re-runs its installer, after first doing the same for the `dotfiles` repo.
local_dotfiles_update() {
    declare -f dotfiles_update > /dev/null && (dotfiles_update "$@") && (
        DOTFILES_LOCAL="${DOTFILES_LOCAL:-~/.dotfiles_local}"
        DOTFILES="$DOTFILES_LOCAL" && dotfiles_update "$@"
    )
}
alias ldfu='local_dotfiles_update'

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
