#!/usr/bin/env sh

# Add scripts to path
path_prepend "$HOME/.dotfiles_local/bin"

# Update local dotfiles
ldfu() {
    declare -f dfu > /dev/null && dfu &&
    (
        cd ~/.dotfiles_local && git pull --ff-only && ./install -q
    )
}

# Setup SSH agent
if [[ -f /mnt/c/Users/256560/SSH_AUTH_SOCK.wsl ]]
then
    export SSH_AUTH_SOCK=/mnt/c/Users/256560/SSH_AUTH_SOCK.wsl
fi

