#!/usr/bin/env sh

# Add scripts to path
path_prepend "$HOME/.dotfiles_local/bin"

# Update local dotfiles
ldfu() {
    declare -f dfu > /dev/null && dfu &&
    (
        cd ~/.dotfiles_local && git pull --ff-only && ./install -q
    )
}

# Setup SSH agent
if [[ -f /mnt/c/Users/256560/SSH_AUTH_SOCK.wsl ]]
then
    export SSH_AUTH_SOCK=/mnt/c/Users/256560/SSH_AUTH_SOCK.wsl
fi

## Autorun for the gpg-relay bridge
SOCAT_PID_FILE=$HOME/.misc/socat-gpg.pid
if [[ -f $SOCAT_PID_FILE ]] && kill -0 $(cat $SOCAT_PID_FILE); then
   : # already running
else
    rm -f "$HOME/.gnupg/S.gpg-agent"
    (trap "rm $SOCAT_PID_FILE" EXIT; socat UNIX-LISTEN:"$HOME/.gnupg/S.gpg-agent,fork" EXEC:'/mnt/c/Users/256560/.dotfiles_local/bin/npiperelay.exe -ei -ep -s -a "C:/Users/256560/AppData/Roaming/gnupg/S.gpg-agent"',nofork </dev/null &>/dev/null) &
    echo $! >$SOCAT_PID_FILE
fi
