name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/brucificus/dotfiles
          ./dotfiles/install.ps1 --except shell
      - run: |
          ./install.ps1
